server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 9102
  adminConnectors:
    - type: http
      port: 9104
swagger:
  resourcePackage: com.ontotext.content.resource