---
swagger: "2.0"
info:
  description: "Content API. Supporting the CRUD on content assets"
  version: "v0.0.1"
  title: "Content API"
  termsOfService: "http://www.yourterms.com"
  contact:
    name: "Jem Rayfield"
    url: "http://ontotext.com"
    email: "jem.rayfield@ontotext.com"
host: "localhost:9102"
basePath: "/content"
tags:
- name: "Content API"
schemes:
- "http"
- "https"
paths:
  /content/{contentId}:
    get:
      tags:
      - "Content API"
      summary: "Get Content by Id"
      description: ""
      operationId: "annotation"
      parameters:
      - name: "contentId"
        in: "path"
        description: "Content Id to be retrieved."
        required: true
        type: "string"
        default: "tsk550fnfym8"
      - name: "X-Request-ID"
        in: "header"
        description: "Transaction Id"
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
          headers:
            X-Cache:
              type: "boolean"
              description: "Explains whether or not a cache was used"
            ETag:
              type: "string"
              description: "Content ETag for cache control"
            Vary:
              type: "string"
              description: "Make sure proxies cache by Vary"
            Allow:
              type: "string"
              description: "CORS Allowed Methods"
        202:
          description: "Processing"
          headers:
            X-Cache:
              type: "boolean"
              description: "Explains whether or not a cache was used"
            ETag:
              type: "string"
              description: "Content ETag for cache control"
            Vary:
              type: "string"
              description: "Make sure proxies cache by Vary"
            Allow:
              type: "string"
              description: "CORS Allowed Methods"
        400:
          description: "Invalid Content Id supplied"
        404:
          description: "Content not found"
